[package]
name = "captchas"
version = "0.1.0"
authors = ["Adam Birtles <nerdopoly@icloud.com>"]

[dependencies]

[[bin]]
name = "part1"
path = "src/part1.rs"

[[bin]]
name = "part2"
path = "src/part2.rs"
